version: '3'


services:
  app:
    build: .
    command: jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root
    volumes:
      - "$PWD:/opt/notebooks"
    ports:
      - "8888:8888"
      - "5000:5000"
    working_dir: /opt/notebooks
